[package]
name = "java_random"
version = "0.1.5"
authors = ["Neil <neilhube12@gmail.com>"]
edition = "2018"
description="The java LCG and random module implementation in rust"
categories=["algorithms","data-structures"]
license="MIT"

[dependencies]
